services:
  - type: web
    name: procurement-system
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn procurement_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
